apiVersion: v1
kind: Namespace
metadata:
  name: tq-BRANCH_ORG_NAME
  annotations:
    description: See https://github.com/josejuan/time-queue
---
apiVersion: v1
kind: Pod
metadata:
  namespace: tq-BRANCH_ORG_NAME
  name: tqserver
  labels:
    type: tqserver
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: tqserver
      image: geodesicsoflearning/tq:server-BRANCH_ORG_NAME
      imagePullPolicy: Always
      env:
        - name: TIMEQ_ENV
          value: "BRANCH_ORG_NAME"
        - name: TIMEQ_DB_DEV_USR
          value: "DEV_DATABASE_USR"
        - name: TIMEQ_DB_DEV_PWD
          value: "DEV_DATABASE_PWD"
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: tq-BRANCH_ORG_NAME
  name: tqserver
spec:
  selector:
    type: tqserver
  ports:
    - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  # currently we use an external dbmg
  name: postgres
  namespace: tq-BRANCH_ORG_NAME
spec:
  type: ExternalName
  externalName: vps-4105a34c.vps.ovh.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingresslive
  namespace: tq-BRANCH_ORG_NAME
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Cache-Status none;
spec:
  tls:
    - hosts:
        - BRANCH_ORG_NAME.tq.WWW_ORG_NAME
  defaultBackend:
    service:
      name: tqserver
      port:
        number: 8080
