name: Time Queue

on:
  push:
    branches:
      - main
      - www

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B clean package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: ebranch
      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/tq-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: geodesicsoflearning/tq:server-${{ steps.ebranch.outputs.branch }}
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/cloud.key
          chmod 600 ~/.ssh/cloud.key
          cat >>~/.ssh/config <<END
          Host cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.K8S_SSH_USER }}
          SSH_KEY: ${{ secrets.K8S_SSH_KEY }}
          SSH_HOST: ${{ secrets.K8S_SSH_HOST }}
      - name: Kubernetes apply
        run: |
          ssh cloud '! microk8s kubectl describe namespace tq-${{ steps.ebranch.outputs.branch }} || microk8s kubectl delete namespace tq-${{ steps.ebranch.outputs.branch }}'
          cat cloud/cloud_common.yml cloud/${GITHUB_REF##*/}_cloud.yml | \
            sed 's/"TIMEQ_MAIL_SUBJECT"/"Time Queue (${{ steps.ebranch.outputs.branch }}): "/g' | \
            sed 's/"TIMEQ_DEPLOYMENT"/"${{ steps.ebranch.outputs.branch }}"/g' | \
            sed 's/"TIMEQ_MAIL_FROM"/"${{ secrets.TIMEQ_MAIL_FROM }}"/g' | \
            sed 's/"TIMEQ_MAIL_HOST"/"${{ secrets.TIMEQ_MAIL_HOST }}"/g' | \
            sed 's/"TIMEQ_MAIL_PASS"/"${{ secrets.TIMEQ_MAIL_PASS }}"/g' | \
            sed 's/"TIMEQ_MAIL_USER"/"${{ secrets.TIMEQ_MAIL_USER }}"/g' | \
            sed 's/DEV_DATABASE_USR/${{ secrets.DEV_DATABASE_USR }}/g' | \
            sed 's/DEV_DATABASE_PWD/${{ secrets.DEV_DATABASE_PWD }}/g' | \
            sed 's/BRANCH_ORG_NAME/${{ steps.ebranch.outputs.branch }}/g' | \
            sed 's/WWW_ORG_NAME/${{ secrets.WWW_ORG_NAME }}/g' | \
            ssh cloud 'microk8s kubectl apply -f -'